<script src="<?php echo e(asset('common/js/jquery.min.js')); ?>"></script>
<script defer src="<?php echo e(asset('common/js/bootstrap.min.js')); ?>"></script>
<script defer src="<?php echo e(asset('common/js/select2.min.js')); ?> "></script>
<script defer src="<?php echo e(asset('common/js/jquery.mCustomScrollbar.min.js')); ?>"></script>
<script defer src="<?php echo e(asset('common/js/popper-core.js')); ?>"></script>
<script defer src="<?php echo e(asset('common/js/tippy.js')); ?>"></script>
<script defer src="<?php echo e(asset('js/main.js')); ?>"></script>
<script defer src="<?php echo e(asset('common/js/jquery-confirm.min.js')); ?>"></script>
<script defer src="<?php echo e(asset('admin/js/main.js')); ?>"></script><?php /**PATH /home/iphihbst/test.iphix.shop/resources/views/layouts/admin/footer_scripts.blade.php ENDPATH**/ ?>